---
- name: Install Ghostty snap
  become: true
  community.general.snap:
    name: ghostty
    state: present

- name: Create Ghostty config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/ghostty"
    state: directory
    mode: "0755"

- name: Deploy Ghostty config
  ansible.builtin.template:
    src: config.j2
    dest: "{{ ansible_env.HOME }}/.config/ghostty/config"
    mode: "0644"
