---
- name: Remove tmux snap
  become: true
  community.general.snap:
    name: tmux
    state: absent
  ignore_errors: true

- name: Install tmux
  become: true
  ansible.builtin.apt:
    name: tmux
    state: present

- name: Install TPM (Tmux Plugin Manager)
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    depth: 1

- name: Deploy .tmux.conf
  ansible.builtin.template:
    src: tmux.conf.j2
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: "0644"

- name: Install TPM plugins
  ansible.builtin.shell:
    cmd: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins"
  changed_when: true
