---
- name: Create nvm directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.nvm"
    state: directory
    mode: "0755"

- name: Install nvm
  ansible.builtin.shell:
    cmd: >
      export NVM_DIR="{{ ansible_env.HOME }}/.nvm" &&
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    executable: /bin/bash

- name: Install Node.js 24 via nvm
  ansible.builtin.shell:
    cmd: >
      export NVM_DIR="{{ ansible_env.HOME }}/.nvm" &&
      . "$NVM_DIR/nvm.sh" &&
      nvm install 24
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node"
    executable: /bin/bash
