op_account: my
atuin_vault: Personal
git_email: brandt@kurowski.net
theme: dark
is_desktop: true
snaps_common:
  - { name: tailscale }
snaps_desktop:
  - { name: code, classic: true }
  - { name: obsidian, classic: true }
  - { name: gimp }
  - { name: spotify }
dock_favorites:
  - org.gnome.Nautilus.desktop
  - 1password.desktop
  - obsidian_obsidian.desktop
  - ghostty_ghostty.desktop
  - firefox.desktop
  - code_code.desktop
  - spotify_spotify.desktop
  - snap-store_snap-store.desktop
