git_email: bkurowski@uceap.universityofcalifornia.edu
theme: light
is_desktop: true
dock_favorites:
  - org.gnome.Nautilus.desktop
  - 1password.desktop
  - obsidian_obsidian.desktop
  - ghostty_ghostty.desktop
  - firefox_firefox.desktop
  - code_code.desktop
  - snap-store_snap-store.desktop
