op_account: team-uceap
atuin_vault: Employee
git_email: bkurowski@uceap.universityofcalifornia.edu
theme: light
is_desktop: true
snaps_common:
  - { name: aws-cli, classic: true }
snaps_desktop:
  - { name: obsidian, classic: true }
dock_favorites:
  - org.gnome.Nautilus.desktop
  - 1password.desktop
  - obsidian_obsidian.desktop
  - ghostty_ghostty.desktop
  - firefox.desktop
  - code.desktop
  - snap-store_snap-store.desktop
